# Generated by Django 4.0.4 on 2022-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='project_name',
            field=models.CharField(default='yaja', max_length=50),
            preserve_default=False,
        ),
    ]
