# Generated by Django 3.1.4 on 2022-12-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20221210_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Agent',
            new_name='agent',
        ),
    ]
